id: hl7.fhir.uv.rfi-ig
canonical: http://hl7.org/fhir/uv/rfi-ig
name: RFI
title: Regulatory Correspondence
description: Standard for structuring List of Quesrions (LOQ), List of Issues (LOI), and decision letters from a health authority to a Market Authorization Holders. 
status: draft
version: 0.1.0
fhirVersion: 5.0.0
copyrightYear: 2025+
releaseLabel: ci-build
publisher:
  name: Gravitate Health Project
  url: https://www.gravitatehealth.eu/
license: CC0-1.0
# dependencies:
#  hl7.fhir.r5.core: 5.0.0
parameters:
  show-inherited-invariants: false
  autoload-resources: true
  produce-jekyll-data: true
  generate-artifacts-page: true
  generate-downloads-page: true
pages:
  index.md:
    title: Home
  use-case.md:
    title: Use Case
  loq-loi.md:
    title: List of Quesrions / Issues
  decisionletter.md:
    title: Decision Letter
  rfi-structure.md:
    title: Request for Information
  terminology.md:
    title: Value Sets
  examples.md:
    title: Examples
menu:
  Home: index.html
  Use Case: use-case.html
  Correspondence Structure: 
    List of Questions / Issues: loq-loi.html
    Decision Letter: decisionletter.html
    Request for Information: rfi-structure.html
  Terminology: terminology.html
  Examples: examples.html
  Artifacts: artifacts.html
