id: hl7.fhir.uv.rcs-ig
canonical: http://hl7.org/fhir/uv/rcs-ig
name: RCS
title: Structured Regulatory Correspondence (SRC)
description: Standard for structuring regulatory correspondence from a health authority to a Market Authorization Holder. This includes List of Questions (LOQ), Response to List of Questions, List of Issues (LOI), Response to List of Issues, Request for Information, Response to Request for Information, and Decision Letters.
status: draft
version: 0.1.0
fhirVersion: 5.0.0
copyrightYear: 2025+
releaseLabel: ci-build
publisher:
  name: Gravitate Health and HL7 Biomedical Research & Regulation (BR&R)
  url: https://www.gravitatehealth.eu/
license: CC0-1.0
# dependencies:
#  hl7.fhir.r5.core: 5.0.0

pages:
  index.md:
    title: Home
  use-case.md:
    title: Use Case
  loq-loi.md:
    title: List of Questions and Issues
  decisionletter.md:
    title: Decision Letter
  rfi-structure.md:
    title: Request for Information
  terminology.md:
    title: Value Sets
  examples.md:
    title: Examples
menu:
  Home: index.html
  Use Case: use-case.html
  Correspondence Types: 
    List of Questions and Issues: loq-loi.html
    Decision Letter: decisionletter.html
    Request for Information: rfi-structure.html
  Terminology: terminology.html
  Examples: examples.html
  Artifacts: artifacts.html
