id: hl7.fhir.uv.rfi-ig
canonical: http://hl7.org/fhir/uv/rfi-ig
name: RFI
title: Request for Information (RFI)
description: Standard for structuring RFIs from health authorities to Market Authorization Holders.
status: draft
version: 0.1.0
fhirVersion: 5.0.0
copyrightYear: 2025+
releaseLabel: ci-build
publisher:
  name: Gravitate Health Project
  url: https://www.gravitatehealth.eu/
license: CC0-1.0
# dependencies:
#  hl7.fhir.r5.core: 5.0.0
parameters:
  show-inherited-invariants: false
  autoload-resources: true
  produce-jekyll-data: true
  generate-artifacts-page: true
  generate-downloads-page: true
pages:
  index.md:
    title: Home
  use-case.md:
    title: Use Case
  rfi-structure.md:
    title: RFI Structure
  terminology.md:
    title: Value Sets
  examples.md:
    title: Examples
menu:
  Home: index.html
  Use Case: use-case.html
  RFI Structure: rfi-structure.html
  Terminology: terminology.html
  Examples: examples.html
  Artifacts: artifacts.html
  Downloads: downloads.html